// @flow
module.exports = {
    SCREEN_TITLE: {
        HOME: 'Home',
        DELIVER: "Deliver shipments",
        ACCEPT: "Accept shipments",
        RETURN: "Return shipments",
        SHIPMENT_DETAILS: "Shipment details",
    },
    COLOR: {
        PRIMARY: '#0F303E',
        DARK_PRIMARY: '#0C2733',
        APP_BACKGROUND: '#F1F1F1',
        BLACK_75: 'rgba(0,0,0,0.75)',
        GREYISH_BROWN: '#565656',
        PALE_GREY_33: 'rgba(231,235,237,0.33)',
        LIGHT_GREY: '#cecece',
        GREY: '#aaaaaa',
        TEXT_ICON: '#FFFFFF',
        ACCENT: '#4CAF50',
        PRIMARY_TEXT: '#212121',
        SECONDARY_TEXT: '#727272',
        DIVIDER: '#B6B6B6',
        BACKGROUND: '#0E3753',
        LIBRARY_PRIMARY: 'paperBlue',
        WHITE: '#FFFFFF',
        LOGIN_GREY_CARD: 'rgba(255,255,255,0.64)',
        PRIMARY_GREEN: '#38ab57',
        BLACK_87: 'rgba(0, 0, 0, 0.87)',
        BLACK_54: 'rgba(0,0,0,0.54)',
        BLACK_27: 'rgba(0,0,0,0.27)',
        GRE_98: '#FAFAFA',
        CHETWODE_BLUE: '#58A2C2',
        LOADER_TRANSPARENT_BACKGROUND: 'rgba(0, 0, 0, 0.3)'
    },
    STRINGS: {
        LOGIN: 'LOGIN',
        INVALID_PASSWORD: 'Invalid password',
        INVALID_USER_NAME: 'Invalid username',
        MOBILE_NUMBER: 'Mobile Number',
        PASSWORD: 'Password',
        LOGIN_ERROR_USERNAME_PASSWORD: 'Wrong username/password',
        LOGIN_ERROR: 'Login failed',
        NETWORK_ERROR_TITLE: 'Slow or no internet connection',
        NETWORK_ERROR_MESSAGE: 'Please wait & try again after a moment',
        SHIPMENTS_TO_ACCEPT: 'Shipments to Accept',
        SHIPMENTS_TO_DELIVER: 'Shipments to Deliver',
        SHIPMENTS_NOT_DELIVERED: 'Shipments not Delivered',
        UPDATE: 'UPDATE',
        DEL: 'DEL',
        DEF: 'DEF',
        CNA: 'CNA',
        WRET: 'WRET',
        WCA: 'WCA',
        DEL_DETAIL: 'Delivered',
        DEF_DETAIL: 'Deferred',
        CNA_DETAIL: 'Customer Not Available',
        WRET_DETAIL: 'Returned',
        WCA_DETAIL: 'Wrong Customer Address',
        CUSTOMER_NAME: 'Customer Name',
        ADDRESS: 'Address',
        CONTACT_NO: 'Contact Number',
        AWB_NO: 'Awb Number',
        PAYMENT_MODE: 'Payment Mode',
        COD: 'Cash On Delivery',
        CALL_MANAGER: 'Call Manager',
        LOGOUT: 'Logout',
        MANAGER_PHONE_ERROR: 'Manager number is not available, Refresh Home Screen',
        SIGNATURE: 'Receiver\'s Signature',
        PROCEED: 'PROCEED',
        SIGNATURE_INSTRUCTION: '[Use fingers to sign and X to clear]',
        SIGNATURE_ALERT_TITLE: 'Signature Mandatory',
        SIGNATURE_ALERT_MESSAGE: 'You cannot proceed without receiver\'s signature.\n\nTake signature and proceed.',
        OK: 'OK',
        CANCEL: 'Cancel',
        AWB: 'Awb',
        ACCEPT: 'ACCEPT',
        ACKNOWLEDGEMENT: 'Acknowledgement',
        SKIP: 'SKIP',
        TAKE_PHOTO: '[Tap here on screen to capture]',
        CLEAR_PHOTO: '[Tap on image to re-take photo]',
        CUSTOMER_PHONE_ERROR: 'Customer number is not available',
        DEF_CALL_CUSTOMER_MSG: 'You need to make call to Customer before changing shipment status to DEF. Call now ?',
        SEARCH_ERROR: 'Failed to get Tweet',
        SERVER_ERROR: 'Server error',
        NETWORK_ERROR: 'Network error',
        ACCEPT_SHIPMENTS_SUCCESSFUL: 'Successfully accepted shipments',
        ACCEPT_SHIPMENTS_FAILED: 'Failed to accept shipments',
    },
    ICONS: {
    },
    SIZE: {
        MEDIUM_TEXT: 16,
        DEFAULT_MARGIN: 16,
        SCREEN_TOP_MARGIN: 20,
        LOGIN_BANNER_HT: 138,
        LOGIN_BANNER_WIDTH: 189,
        LOGIN_BANNER_SPACE: 88
    },
    CONFIG: {
        IMAGE_ROOT_PATH: 'Fellini',
        SIGNATURE_FILENAME: 'sign',
        PHOTO_FILENAME: 'photo'
    },

    SHIPMENT_SCREENS: {
        ACCEPT: "accept",
        DELIVERY: "deliver",
        RETURN: "return",
    }
};
